/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BorrowItem = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'ownerName' : IDL.Text,
  'name' : IDL.Text,
  'category' : IDL.Text,
});
export const FoodAlert = IDL.Record({
  'id' : IDL.Nat,
  'source' : IDL.Text,
  'claimed' : IDL.Bool,
  'quantity' : IDL.Nat,
  'timeLeft' : IDL.Text,
});
export const StudyRoom = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'capacity' : IDL.Nat,
  'roomNo' : IDL.Text,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'avatarInitials' : IDL.Text,
  'name' : IDL.Text,
  'greenPoints' : IDL.Nat,
  'department' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'awardGreenPoints' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'bookStudyRoom' : IDL.Func([IDL.Nat], [], []),
  'claimBorrowItem' : IDL.Func([IDL.Nat], [], []),
  'claimFoodAlert' : IDL.Func([IDL.Nat], [], []),
  'getAllBorrowItems' : IDL.Func([], [IDL.Vec(BorrowItem)], ['query']),
  'getAllFoodAlerts' : IDL.Func([], [IDL.Vec(FoodAlert)], ['query']),
  'getAllStudyRooms' : IDL.Func([], [IDL.Vec(StudyRoom)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BorrowItem = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'ownerName' : IDL.Text,
    'name' : IDL.Text,
    'category' : IDL.Text,
  });
  const FoodAlert = IDL.Record({
    'id' : IDL.Nat,
    'source' : IDL.Text,
    'claimed' : IDL.Bool,
    'quantity' : IDL.Nat,
    'timeLeft' : IDL.Text,
  });
  const StudyRoom = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'capacity' : IDL.Nat,
    'roomNo' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'avatarInitials' : IDL.Text,
    'name' : IDL.Text,
    'greenPoints' : IDL.Nat,
    'department' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'awardGreenPoints' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'bookStudyRoom' : IDL.Func([IDL.Nat], [], []),
    'claimBorrowItem' : IDL.Func([IDL.Nat], [], []),
    'claimFoodAlert' : IDL.Func([IDL.Nat], [], []),
    'getAllBorrowItems' : IDL.Func([], [IDL.Vec(BorrowItem)], ['query']),
    'getAllFoodAlerts' : IDL.Func([], [IDL.Vec(FoodAlert)], ['query']),
    'getAllStudyRooms' : IDL.Func([], [IDL.Vec(StudyRoom)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };