/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BorrowItem {
  'id' : bigint,
  'status' : string,
  'ownerName' : string,
  'name' : string,
  'category' : string,
}
export interface FoodAlert {
  'id' : bigint,
  'source' : string,
  'claimed' : boolean,
  'quantity' : bigint,
  'timeLeft' : string,
}
export interface RequestItem {
  'id' : bigint,
  'title' : string,
  'postedBy' : string,
  'fulfilled' : boolean,
  'deadline' : string,
  'category' : string,
}
export interface StudyRoom {
  'id' : bigint,
  'status' : string,
  'capacity' : bigint,
  'roomNo' : string,
  'location' : string,
}
export interface UserProfile {
  'id' : Principal,
  'avatarInitials' : string,
  'name' : string,
  'greenPoints' : bigint,
  'department' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addRequest' : ActorMethod<[string, string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'awardGreenPoints' : ActorMethod<[bigint], undefined>,
  'bookStudyRoom' : ActorMethod<[bigint], undefined>,
  'claimBorrowItem' : ActorMethod<[bigint], undefined>,
  'claimFoodAlert' : ActorMethod<[bigint], undefined>,
  'fulfillRequest' : ActorMethod<[bigint], undefined>,
  'getAllBorrowItems' : ActorMethod<[], Array<BorrowItem>>,
  'getAllFoodAlerts' : ActorMethod<[], Array<FoodAlert>>,
  'getAllRequests' : ActorMethod<[], Array<RequestItem>>,
  'getAllStudyRooms' : ActorMethod<[], Array<StudyRoom>>,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<UserProfile>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'releaseStudyRoom' : ActorMethod<[bigint], undefined>,
  'returnBorrowItem' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCallerUserProfile' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];